In [1]:
import numpy as np
import pandas as pd

# Definir las cargas aplicadas (kg)
cargas = np.array([1, 2, 3, 4, 5, 6])

# Definir las deformaciones para cada tipo de aleación
deformaciones_a1 = np.array([0, 0.5, 1.2, 2, 3, 4])
deformaciones_a2 = np.array([0, 0.6, 1.4, 2.5, 3.8, 5])
deformaciones_a3 = np.array([0, 0.7, 1.5, 2.7, 4, 5.5])

# Construir la matriz X
X = np.column_stack((np.ones(len(cargas)), cargas, cargas**2))

# Construir la matriz de deformaciones
y = np.concatenate((deformaciones_a1, deformaciones_a2, deformaciones_a3))

# Crear un DataFrame de pandas para visualizar la matriz
data = np.column_stack((X, y))
df = pd.DataFrame(data, columns=['Intercepto', 'Carga', 'Carga^2', 'Deformación'])

print(df)

/tmp/ipykernel_17127/3901947996.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 6 and the array at index 1 has size 18

In [2]:
import numpy as np
import pandas as pd

# Definir las cargas aplicadas (kg)
cargas = np.array([1, 2, 3, 4, 5, 6])

# Definir las deformaciones para cada tipo de aleación
deformaciones_a1 = np.array([0, 0.5, 1.2, 2, 3, 4])
deformaciones_a2 = np.array([0, 0.6, 1.4, 2.5, 3.8, 5])
deformaciones_a3 = np.array([0, 0.7, 1.5, 2.7, 4, 5.5])

# Construir la matriz X
X = np.column_stack((np.ones(len(cargas)), cargas, cargas**2))

# Construir la matriz de deformaciones
y = np.concatenate((deformaciones_a1, deformaciones_a2, deformaciones_a3))

# Crear un DataFrame de pandas para visualizar la matriz
data = np.column_stack((X, y))
df = pd.DataFrame(data, columns=['Intercepto', 'Carga', 'Carga^2', 'Deformación'])

print(df)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 6 and the array at index 1 has size 18

In [3]:
import numpy as np
import pandas as pd

# Definir las cargas aplicadas (kg)
cargas = np.array([1, 2, 3, 4, 5, 6])

# Definir las deformaciones para cada tipo de aleación
deformaciones_a1 = np.array([0, 0.5, 1.2, 2, 3, 4])
deformaciones_a2 = np.array([0, 0.6, 1.4, 2.5, 3.8, 5])
deformaciones_a3 = np.array([0, 0.7, 1.5, 2.7, 4, 5.5])

# Construir la matriz X
X = np.column_stack((np.ones(len(cargas)), cargas, cargas**2))

# Construir la matriz de deformaciones
y = np.concatenate((deformaciones_a1, deformaciones_a2, deformaciones_a3))

# Crear un DataFrame de pandas para visualizar la matriz
data = np.column_stack((X, y))
df = pd.DataFrame(data, columns=['Intercepto', 'Carga', 'Carga^2', 'Deformación'])

print(df)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 6 and the array at index 1 has size 18

In [4]:
import numpy as np

# Supongamos que las cargas son [1, 2, 3, 4, 5, 6]
cargas = np.array([1, 2, 3, 4, 5, 6])

# Repetir las cargas para cada aleación
cargas = np.repeat(cargas, 3)

# Crear la matriz X con una columna de unos (para el intercepto), una columna para las cargas y una columna para las cargas al cuadrado
X = np.column_stack((np.ones(len(cargas)), cargas, cargas**2))

# Supongamos que los coeficientes β son [1, 2, 3]
beta = np.array([1, 2, 3])

# Calcular y
y = np.dot(X, beta)

print("Matriz X:")
print(X)
print("Vector y:")
print(y)

Matriz X:
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  2.  4.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  3.  9.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]
 [ 1.  4. 16.]
 [ 1.  4. 16.]
 [ 1.  5. 25.]
 [ 1.  5. 25.]
 [ 1.  5. 25.]
 [ 1.  6. 36.]
 [ 1.  6. 36.]
 [ 1.  6. 36.]]
Vector y:
[  6.   6.   6.  17.  17.  17.  34.  34.  34.  57.  57.  57.  86.  86.
  86. 121. 121. 121.]
